name: ${name}
version: ${version}
main: ${main}
api-version: "${apiVersion}"
author: ${author}
description: ${description}
softdepend: [PlaceholderAPI]
libraries:
  - org.postgresql:postgresql:42.7.7
  - org.xerial:sqlite-jdbc:3.50.3.0
  - com.zaxxer:HikariCP:6.3.0

commands:
  manhunt:
    description: Manage a Manhunt match.
    usage: /manhunt help
    aliases: [mh]

permissions:
  jmanhunt.command.help:
    description: Use /manhunt help.
    default: true
  jmanhunt.command.status:
    description: View the current Manhunt status.
    default: true
  jmanhunt.command.setplayer:
    description: Assign players to Manhunt roles.
    default: op
  jmanhunt.command.start:
    description: Start a Manhunt match.
    default: op
  jmanhunt.command.end:
    description: End an active Manhunt match.
    default: op
  jmanhunt.command.reload:
    description: Reload JManhunt configuration.
    default: op
  jmanhunt.command.modifiers:
    description: Change JManhunt modifiers and boolean settings.
    default: op
  jmanhunt.command.worldengine:
    description: View world-engine settings.
    default: op
  jmanhunt.hunter:
    description: Allows a player to become a hunter.
    default: true
  jmanhunt.speedrunner:
    description: Allows a player to become a speedrunner.
    default: true
